name: direnv-action
author: Shikanime Studio
branding:
  icon: globe
  color: gray-dark
description: Direnv environment
inputs:
  extra-args:
    description: Extra arguments to pass to `nix run`
    required: false
    default: ""
  registry:
    description: Nix registry to use
    required: false
    default: nixpkgs
runs:
  using: composite
  steps:
    - name: Direnv with nix-direnv and export environment
      shell: bash
      run: |
        nix run "${{ inputs.registry }}#direnv" ${{ inputs.extra-args }} -- \
          allow
        nix run "${{ inputs.registry }}#direnv" ${{ inputs.extra-args }} -- \
          export gha > "$GITHUB_ENV"
