name: setup-direnv-action
author: Shikanime Studio
branding:
  icon: globe
  color: gray-dark
description: Setup direnv environment
runs:
  using: composite
  steps:
    - name: Setup direnv with nix-direnv and export environment
      shell: bash
      run: |
        nix run nixpkgs#direnv allow
        nix run nixpkgs#direnv -- direnv export gha > "$GITHUB_ENV"
